### ISSUE TITLE
[PyPi] md2rst parsing problem

### ISSUE THREAD

**Issue by maxkrivich** [miyakogi/m2r#11]
I'm using m2r for parse my [README.md](https://github.com/maxkrivich/SlowLoris/blob/master/README.md) file and after publication on [pypi](https://pypi.python.org/pypi/PySlowLoris) formatting just broke. 

my parser code in setup.py
```py
try:
    from m2r import parse_from_file

    LONG_DESCRIPTION = parse_from_file('README.md')
except ImportError:
    with open('README.md') as f:
        LONG_DESCRIPTION = f.read()
```

**Comment by miyakogi** [comment]
Thank you for reporting.

But sorry, I couldn't find where is broken.
Could you let me know where is different from what you expected?

This is a screenshot of the pypi page.

![image](https://user-images.githubusercontent.com/3213998/29832836-76f61394-8d24-11e7-81e1-4262931e5784.png)

**Comment by maxkrivich** [comment]
@miyakogi I fix, but a problem was in wrong License title parsing.

**Comment by maxkrivich** [comment]
https://github.com/maxkrivich/SlowLoris/blob/cada90037959cda4268ec30b7854ff47e7c2ccc2/README.md 
in License

**Comment by miyakogi** [comment]
Thank you, I understand the problem.

In reStructuredText, headings must appear its order in the document.
If you use `###` before `##`, rst converts `###` to `<h2>` tag and `##` to `<h3>` tag in HTML.

It is defined in the spec of rst, so m2r cannot fix it, sorry.
http://docutils.sourceforge.net/docs/user/rst/quickstart.html#sections

**Comment by maxkrivich** [comment]
@miyakogi ok, thanks!
