### ISSUE TITLE
(WARNING/2) Title underline too short.

### ISSUE THREAD

**Issue by Lonersun** [miyakogi/m2r#12]
hi,
    When i execute the 'make html' command prompt me:
`WARNING: error_doc.md:3: (WARNING/2) Title underline too short.
三、错误对照表
-------
`
This is the contents of error_doc.md 
`

## 三、错误对照表

|错误码|错误名称      |Message                |说明            |
|-----|------------|-----------------------|----------------|
|0    |Api Runtime Error |Runtime api error occurred.     | |`

I do not know whether it is caused by Chinese, Hope to get your help.
                                    
                                                                                                                                             Thanks!

**Comment by miyakogi** [comment]
Thank you for reporting issue!
It was a bug of m2r.

I have fixed it now and released the new version (v0.1.12).
please update m2r and try again.

**Comment by Lonersun** [comment]
Thanks，I have passed the test， good！
