### ISSUE TITLE
Document header level scheme used in rst output.

### ISSUE THREAD

**Issue by waylan** [miyakogi/m2r#13]
The header level scheme is defined in [m2r.py#L177-L184][1]. However, if a parent `rst` file uses a different scheme and then "mincludes" a Markdown file, there is likely to be a `Title level inconsistent` error. At the very least, it should be documented that the parent `rst` file needs to use the same scheme (`=` for level 1, `-` for level 2, etc.). 

For example, this should work fine:

```rst
Parent Header
=============

.. minclude:: child.md
```

Whereas this would likely raise a `Title level inconsistent` error:

```rst
Parent Header
-------------

.. minclude:: child.md
```

See [this][2] for an actual report in the wild.

As a reminder, the [reStructuredText Spec][3] explains:

> Rather than imposing a fixed number and order of section title adornment styles, the order enforced will be the order as encountered. The first style encountered will be an outermost title (like HTML H1), the second style will be a subtitle, the third will be a subsubtitle, and so on.
> 
> ...
> 
> All section title styles need not be used, nor need any specific section title style be used. However, a document must be consistent in its use of section titles: once a hierarchy of title styles is established, sections must use that hierarchy.

Therefore, the parent document could use any number of different schemes by ordering there headers differently, Of course, the parent and child (when including one document in another) must be consistent. However, as users of M2R are not directly authoring the child document as `rst`, they would not know what scheme is being used. At the least it should be documented. As best, M2R could detect the scheme used in the parent file and use that same scheme when generating the included child.

[1]: https://github.com/miyakogi/m2r/blob/master/m2r.py#L177-L184
[2]: https://stackoverflow.com/q/46278683/866026
[3]: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#sections

**Comment by waylan** [comment]
As M2R does not ever output overline-and-underline styles, perhaps the documentation should simply suggest that overline-and-underline styles be used exclusively in the parent document to avoid any conflict. After all the spec states:

> Underline-only adornment styles are distinct from overline-and-underline styles that use the same character.

**Comment by miyakogi** [comment]
Thank you for reporting and answering the question on the stackoverflow.
I will update document and consider whether it's possible to add options to change header level scheme.
