### ISSUE TITLE
Relatively linking to documents

### ISSUE THREAD

**Issue by ryan-lane** [miyakogi/m2r#15]
Does m2r support markdown links to other documents, when using sphinx? With recommonmark, if you link to an md doc, it'll parse that and make a link to the related html doc. It seems with m2r that it's just making relative html links, with the exact contents of the link. I'm trying to keep some compatibility between github docs and sphinx generated docs, so would like to be able to use relative links to the .md files, like in recommonmark.

Is this possible in m2r?

**Comment by miyakogi** [comment]
Thank you for PR.
Merged and released as v0.1.15.
