### ISSUE TITLE
Support for 'title' in links

### ISSUE THREAD

**Issue by chernals** [miyakogi/m2r#21]
The conversion of markdown links with title does not work:

`[http://localhost:8888](http://localhost:8888 "Jupyter Notebook")`

**Comment by miyakogi** [comment]
Currently title of links is not supported, sorry.

**Comment by miyakogi** [comment]
I have implemented it on `dev` branch.
Could you try it?

```
pip install -U git+https://github.com/miyakogi/m2r.git
```

**Comment by miyakogi** [comment]
Released (v0.1.14)
