### ISSUE TITLE
Sphinx 1.8.0 incompatibility

### ISSUE THREAD

**Issue by papakai** [miyakogi/m2r#23]
I've added 'm2r' as described to the sphinx extensions list, source_suffix got also reviewed accordingly.
```python
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.intersphinx',
    'sphinxcontrib.log_cabinet',
    'm2r'
]

source_suffix = ['.rst', '.md']
```

Then I get the following error when I trigger the documentation generator.

```bash
Extension error:
source_parser for 'restructuredtext' is already registered
Makefile:22: recipe for target 'html' failed
make: *** [html] Error 2
```

```bash
$ sphinx-apidoc --version
sphinx-apidoc 1.8.0+
```

'm2r' got installed by using pip3.
```bash
$ pip3 install m2r
```

**Comment by papakai** [comment]
As I am not doing this all the day and for helping others too, this should do it:
```bash
pip3 install -e  git://github.com/miyakogi/m2r@dev#egg=m2r
```

**Comment by miyakogi** [comment]
Thank you for commands!

**Comment by papakai** [comment]
Yes, this issue is solved in dev branch!

**Comment by papakai** [comment]
I've noticed some other visual issue with markdown links, but for that I will open a new issue.
Thanks for having fixed this that fast. Very appreciated!

**Comment by miyakogi** [comment]
Thank you for checking it!
