### ISSUE TITLE
Missing Git tags for releases

### ISSUE THREAD

**Issue by felixonmars** [miyakogi/m2r#4]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by miyakogi** [comment]
I add git tags v0.1.7 and later, thanks :)

**Comment by felixonmars** [comment]
You might need to git push --tags too :P

**Comment by miyakogi** [comment]
Sorry, I have pushed now, thanks

**Comment by felixonmars** [comment]
0.1.9 seems to be missing again :3

**Comment by miyakogi** [comment]
sorry...
i added `release` make target not to forget again
https://github.com/miyakogi/m2r/commit/56f30489f9c1da714f31f6aa7d1ed30972ad9e81
